on:
  push:

jobs:
  build-base:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: clysec/alpine-php/.github/workflows/base.yml@main
    with:
      php_version: '8.2'
    secrets:
      X_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build-base-devcontainer:
    needs: build-base
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: clysec/alpine-php/.github/workflows/base.yml@main
    with:
      php_version: '8.2'
      variant: 'devcontainer'
    secrets:
      X_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  