on:
  push:
    branches:
      - disabled
  # schedule:
  #   - cron: '10 3 * * 0'
      
      

jobs:
  build-base:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: clysec/alpine-php/.github/workflows/base.yml@main
    with:
      php_version: "8.4"
      alpine_version: "3.22"
      variant: ""
    secrets:
      X_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_PASSWORD }}

  build-devcontainer:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: clysec/alpine-php/.github/workflows/base.yml@main
    with:
      php_version: "8.4"
      alpine_version: "3.22"
      variant: "devcontainer"
    secrets:
      X_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_PASSWORD }}