on:
  workflow_call:
    inputs:
      php_version:
        description: 'The PHP version to build for'
        required: true
        type: string
      
      alpine_version:
        description: 'The Alpine version to build for'
        type: string
        default: '3.22'
      
      variant:
        description: 'The variant to build'
        type: string
        default: ''
    
    secrets:
      X_GITHUB_TOKEN:
        description: 'GitHub token'
        required: true

      X_DOCKERHUB_USER:
        description: 'Docker Hub username'
        required: false
      
      X_DOCKERHUB_TOKEN:
        description: 'Docker Hub token'
        required: false

      X_CYCR_USER:
        description: 'CYCR user'
        required: false

      X_CYCR_KEY:
        description: 'CYCR key'
        required: false

jobs:
  build-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: clysec
          password: ${{ secrets.X_GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.X_DOCKERHUB_USER }}
          password: ${{ secrets.X_DOCKERHUB_TOKEN }}
    
      - name: Login to cycr.io
        uses: docker/login-action@v2
        with:
          registry: cycr.io/alpine
          username: ${{ secrets.X_CYCR_USER }}
          password: ${{ secrets.X_CYCR_KEY }}

      - name: Get PHP commit version
        id: php_commit_sha
        run: |
          cd base/php
          echo "PHP_COMMIT_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: depot/setup-action@v1
      - uses: depot/build-push-action@v1
        with:
          project: pb9l5sd9m3
          context: ./unit
          file: ./unit/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            PHP_VERSION=${{ inputs.php_version }}
            ALPINE_VERSION=${{ inputs.alpine_version }}
          tags: |
            cycr.io/alpine/unit:${{ inputs.php_version }}-alpine${{ inputs.alpine_version }}${{ (inputs.variant != '' && '-') || '' }}${{ inputs.variant }}
            ${{ (inputs.php_version == '8.4' && 'cycr.io/alpine/unit:latest') || '' }}${{ (inputs.variant != '' && inputs.php_version == '8.4' && '-') || '' }}${{ (inputs.php_version == '8.4' && inputs.variant) || '' }}  
            ghcr.io/clysec/alpine-unit:${{ inputs.php_version }}-alpine${{ inputs.alpine_version }}${{ (inputs.variant != '' && '-') || '' }}${{ inputs.variant }}
            ${{ (inputs.php_version == '8.4' && 'ghcr.io/clysec/alpine-unit:latest') || '' }}${{ (inputs.variant != '' && inputs.php_version == '8.4' && '-') || '' }}${{ (inputs.php_version == '8.4' && inputs.variant) || '' }}  
            docker.io/clysec/alpine-unit:${{ inputs.php_version }}-alpine${{ inputs.alpine_version }}${{ (inputs.variant != '' && '-') || '' }}${{ inputs.variant }}
            ${{ (inputs.php_version == '8.4' && 'docker.io/clysec/alpine-unit:latest') || '' }}${{ (inputs.variant != '' && inputs.php_version == '8.4' && '-') || '' }}${{ (inputs.php_version == '8.4' && inputs.variant) || '' }}  